# Generated by Django 5.1.1 on 2024-11-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakes', '0003_bet_daily_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='next_multiplier',
        ),
    ]
