# Generated by Django 5.1.1 on 2024-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakes', '0004_remove_bet_next_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='nextState',
            field=models.CharField(choices=[('<250', '<250'), ('250-500', '250-500'), ('500-1000', '500-1000'), ('1000-2000', '1000-2000'), ('2000-4000', '2000-4000'), ('4000-8000', '4000-8000'), ('8000-12000', '8000-12000'), ('12000-20000', '12000-20000'), ('20000-30000', '20000-30000'), ('30000-45000', '30000-45000'), ('45000-80000', '45000-80000'), ('>80000', '>80000')], default='<250', max_length=15),
            preserve_default=False,
        ),
    ]
