# Generated by Django 5.1.1 on 2024-11-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakes', '0007_bet_method_betpending_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='number_of_bets_day',
            field=models.IntegerField(default=0),
        ),
    ]
